doc: Update README.md
bitcoindevkit/bdk pull request #1085
Opened 2023-08-21 12:58 UTC by danielabrozzoni

### Description

- Fixes the release timeline
- Adds an explanation for the crates under `example-crates`

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

2023-08-21 13:18 UTC, vladimirfomene commented on README.md
> +- [`example_`](./example-crates/example_electrum): A command line Bitcoin wallet application built on top of `example_cli` and the `electrum` crate. It shows the power of the bdk tools (`chain` + `fi
I think you meant to write [`example_electrum`]

2023-08-21 13:19 UTC, vladimirfomene commented
I also found myself confused about the difference between `example-crates/example_*` and `example-crates/wallet_*`. This will be very useful for our users

2023-08-21 16:56 UTC, realeinherjar reviewed
I think it would be nice to add the same naming convention in `bdk_esplora`.

2023-08-21 16:56 UTC, realeinherjar commented on README.md
> +- [`wallet_esplora`](./example-crates/wallet_esplora): Uses the `Wallet` to sync and spend using Esplora.
```suggestion
- [`wallet_esplora`](./example-crates/wallet_esplora): Uses the `Wallet` to sync and spend using Esplora blocking interface.
```

2023-08-21 17:00 UTC, notmandatory requested changes

2023-08-21 17:00 UTC, notmandatory commented on README.md
>  [`esplora-client`]: https://docs.rs/esplora-client/0.3.0/esplora_client/
Overall like the changes, just needs some link fixes. Better not to hard code the versions so we don't need to keep updating them. Also need to add `bdk_chain`.
```suggestion
[`esplora-client`]: https://docs.rs/esplora-client/
[`electrum-client`]: https://docs.rs/electrum-client/
[`bdk_chain`]: https://docs.rs/bdk-chain/
```

2023-08-22 09:51 UTC, danielabrozzoni commented
Thanks everyone, updated.

> I think it would be nice to add the same naming convention in bdk_esplora.

@realeinherjar can you clarify? I haven't added `example_esplora` to the list of `example_crates` as it's not merged yet. Or were you referring to something else?

2023-08-22 10:28 UTC, realeinherjar commented
> @realeinherjar can you clarify? I haven't added `example_esplora` to the list of `example_crates` as it's not merged yet. Or were you referring to something else?

@danielabrozzoni just the naming conventions for consistency.
At the [`bdk_esplora` docs](https://docs.rs/bdk_esplora/0.3.0/bdk_esplora/) we have this:
<img width="975" alt="image" src="https://github.com/bitcoindevkit/bdk/assets/136860407/e5f9aca8-d867-4973-8fb2-fbf885d7bdaf">

So why not add the "blocking" here as well?

2023-08-22 12:05 UTC, danielabrozzoni commented
Right, I pushed a commit renaming `wallet_esplora` to `wallet_esplora_blocking`

2023-08-23 14:37 UTC, danielabrozzoni commented
Rebased, CI is fixed now.

2023-08-23 16:10 UTC, notmandatory approved these changes

2023-08-23 16:11 UTC, notmandatory approved these changes
ACK 2263a58448f5f04a74e076132aea93f21c584bc0

2023-08-24 12:25 UTC, evanlinjin approved these changes
ACK 2263a58448f5f04a74e076132aea93f21c584bc0

2023-08-24 12:27 UTC, merged