chore: move balance type and anchors mod to chain_data
bitcoindevkit/bdk pull request #1283
Opened 2024-01-16 21:53 UTC by startup-dreamer

### Description

Tries to Fix: #1173 

Moved anchore mod (dropped `tx_data_traits.rs`) and `Balance` type to `chain_data.rs` as suggested in [This comment](https://github.com/bitcoindevkit/bdk/issues/1173#issuecomment-1893094776)

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

2024-01-17 12:20 UTC, LLFourn requested changes

2024-01-17 12:20 UTC, LLFourn commented on crates/chain/src/chain_data.rs
> +/// Balance, differentiated into various categories.
`Balance` doesn't really make sense here can we just put it in `balance.rs` and `pub use balance::*` from `lib.rs`.

2024-02-16 21:35 UTC, startup-dreamer commented
Note (unrelated to PR): GitHub was acting weird for me, that's why this took so long, and I took this issue. I wanted to complete this. Apologies for the delay, @ValuedMammal. Let me know if there are any changes to make. Everything is working fine now.

2024-03-18 17:02 UTC, ValuedMammal commented
Approach NACK

2024-03-18 18:32 UTC, startup-dreamer commented
> Approach NACK

Got it also it's been stale for soo long closing this PR.

2024-03-18 18:32 UTC, closed without merging