doc(wallet): improve docs for `Wallet::sent_and_received`
bitcoindevkit/bdk pull request #1285
Opened 2024-01-17 19:19 UTC by ValuedMammal

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

2024-01-18 06:58 UTC, evanlinjin requested changes
Please stick to this format when documenting components:

```
[short sentence explaining what it is]

[more detailed explanation]

[at least one code example that users can copy/paste to try it]

[even more advanced explanations if necessary]
```

Ref: https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#documenting-components

2024-01-18 06:58 UTC, evanlinjin commented on crates/bdk/src/wallet/mod.rs
> +    /// by the wallet.
```suggestion
    /// Compute the `tx`'s sent and received amounts (in satoshis).
    ///
    /// This method returns a tuple `(sent, received)`. Sent is the summation of the tx's output amounts going to non-tracked script pubkeys. Received is the summation of all inputs amounts.
```

2024-01-18 06:59 UTC, evanlinjin commented
I just realized, I rather have all these doc changes as a single PR. Separate commits for different crates are fine. Thanks for this work.

2024-01-18 10:54 UTC, danielabrozzoni commented
> I just realized, I rather have all these doc changes as a single PR (this may also be easier for you?). Separate commits for different crates are fine. Thanks for this work.

I agree that in the future one PR with separate commits is better, but for now, I'm ok with reviewing separate PRs :)

2024-01-18 15:27 UTC, ValuedMammal commented on crates/bdk/src/wallet/mod.rs
> +    /// by the wallet.
thank you

2024-01-18 15:59 UTC, thunderbiscuit commented
Pardon me for asking but... where is this issue that I opened? Or was it a Discord comment maybe? It's vaguely familiar but I'd love to read back what I wrote 😆🤣.

2024-01-18 16:24 UTC, ValuedMammal commented
[linked discord discussion](https://discord.com/channels/753336465005608961/753367451319926827/1179447370849714286)

2024-01-19 15:36 UTC, evanlinjin approved these changes
ACK 08b745ec9f16fa8ef18b0d9c92feb9d8ab87a184

2024-01-19 15:38 UTC, merged