Expose `SpkIterator::new_with_range`
bitcoindevkit/bdk pull request #1294
Opened 2024-01-22 06:32 UTC by evanlinjin

### Description

This method is useful, I'm not sure why it is not public.

I've also updated the docs and tests.

### Changelog notice

Added
* Expose `SpkIterator::new_with_range`

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature

2024-01-22 08:44 UTC, LLFourn requested changes

2024-01-22 08:44 UTC, LLFourn commented on crates/chain/src/spk_iter.rs
> +    /// The end bound of the range will be shortened to 0 (inclusive) for non-wildcard descriptors
"the end bound of the range will be shortened to 0 (inclusive)" is a very complicated way of saying "non-wildcard descriptors will only emit a single item".

2024-01-22 08:44 UTC, LLFourn commented on crates/chain/src/spk_iter.rs
> +            end = 1;
what happens if we just remove this. It seems to be checked in `next`. Looks unnecessary.

2024-01-23 05:02 UTC, evanlinjin commented on crates/chain/src/spk_iter.rs
> +            end = 1;
Removed.

2024-01-23 16:46 UTC, danielabrozzoni approved these changes
utACK 8305e648494cbdd1f6438904ec367f8442fba606

2024-01-23 16:46 UTC, danielabrozzoni commented on crates/chain/src/spk_iter.rs
> +        assert_eq!(
I'm not sure why these tests are being added, but I won't complain about adding new tests 😛

2024-01-25 10:53 UTC, LLFourn approved these changes
ACK 8305e648494cbdd1f6438904ec367f8442fba606

2024-01-25 10:56 UTC, LLFourn approved these changes
ACK 51bd01b3dd3d68c1628d74be9dc6d0f1cf1f15fe

2024-01-25 11:57 UTC, merged