refactor(chain)!: Remove `Anchor` trait and make anchors unique to (Txid, BlockId)
bitcoindevkit/bdk pull request #1515
Opened 2024-07-17 13:52 UTC by LagginTimes

Resolves #1507.

### Description

The `Anchor` trait has been removed and anchors are now unique to (`Txid`, `BlockId`).

### Notes to the reviewers

Documentation have been mostly untouched and need to be written/updated.

### Changelog notice

* `Anchor` trait has been removed.
* `Anchor` type and `BlockTime` struct have been added to `bdk_chain`.

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

2024-07-18 02:26 UTC, notmandatory reviewed
Overall looks like a nice simplification making `Anchor` a concrete type, and replacing `ConfirmationBlockTime` with `BlockTime`.  I primarily focused on changes in `tx_data_traits.rs` as the rest of the changes are downstream. 

Once docs are done this looks good to me.  

@evanlinjin is it OK to merge this one before #1514 ?

2024-07-18 10:26 UTC, evanlinjin requested changes
This is an initial look. Thanks for pushing so much work out in short notice.

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/src/chain_data.rs
> +    Confirmed((Anchor, AM)),
```suggestion
    Confirmed(Anchor, A),
```

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/src/chain_data.rs
> +    Confirmed((Anchor, AM)),
I also reckon `A` is a better name for the type parameter haha.

2024-07-18 10:26 UTC, evanlinjin commented on crates/bitcoind_rpc/tests/test_emitter.rs
> +    let mut indexed_tx_graph = IndexedTxGraph::<BlockTime, _>::new({
For this example, `A` can be `()`.

Are we actually using `BlockTime` in these tests? I'm assuming we can just remove it.

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/src/tx_graph.rs
> +pub struct TxGraph<AM = BlockTime> {
This is a change to default behavior (having a block-time by default). I'm curious about the intentions for this change.

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/src/tx_graph.rs
> +    txs: HashMap<Txid, (TxNodeInternal, BTreeMap<Anchor, AM>)>,
```suggestion
    txs: HashMap<Txid, (TxNodeInternal, BTreeSet<BlockId>)>,
```
Anchor contains the txid. It does not make as part of the value of something keyed by txid.

Also we can lookup the `A` (anchor meta) from `anchors`.

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/src/tx_graph.rs
> +    pub anchors: &'a BTreeMap<Anchor, AM>,
```suggestion
    pub anchors: Range<'a, Anchor, AM>,
```

I'm not sure if this will work? Getting a range from `TxGraph::anchors`.

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/src/tx_graph.rs
> +            .collect::<BTreeMap<_, _>>();
We also need to compare values to see if things are changed. This means values `A` (anchor meta) needs to impl `PartialEq` for this.

This also needs a test.

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/src/tx_graph.rs
> +impl<AM: Ord + Clone> TxGraph<AM> {
We don't need the `Ord` bound.

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/src/indexed_tx_graph.rs
> +    AM: AnchorMetaFromBlock + core::fmt::Debug + Clone + Eq + PartialOrd + Ord + core::hash::Hash,
Are all these bounds needed?

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/src/tx_graph.rs
> +impl<AM: Ord> AsRef<TxGraph<AM>> for TxGraph<AM> {
Unnecessary bound.

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/tests/common/mod.rs
> +            bdk_chain::BlockTime::new(100),
`()` might be a better default for tests. Unless we need blocktime for the tests.

2024-07-18 10:26 UTC, evanlinjin commented on crates/chain/tests/test_tx_graph_conflicts.rs
> +                    anchors: &[anchor!(1, "B")],
Beautiful.

2024-07-18 10:28 UTC, evanlinjin commented
@notmandatory I prefer we rebase this on top of #1514 since that PR is more "final" than this one.

2024-07-18 13:50 UTC, evanlinjin commented
As discussed privately, it makes sense to rm `TxGraph::anchors` field.

```rust
pub struct TxGraph<AM = BlockTime> {
    // all transactions that the graph is aware of in format: `(tx_node, tx_anchors)`
    txs: HashMap<Txid, (TxNodeInternal, BTreeMap<BlockId, AM>)>,
    spends: BTreeMap<OutPoint, HashSet<Txid>>,
    last_seen: HashMap<Txid, u64>,


    // This atrocity exists so that `TxGraph::outspends()` can return a reference.
    // FIXME: This can be removed once `HashSet::new` is a const fn.
    empty_outspends: HashSet<Txid>,
}
```

See P.O.C: https://github.com/bitcoindevkit/bdk/commit/63d9e6a8973e0657ab6d9d9eadac8e544c15125c

2024-07-19 11:30 UTC, evanlinjin commented
This is great work. Unfortunately, I do not think we have enough time to push this into `v1.0.beta` (as discussed).

2024-07-19 20:01 UTC, notmandatory commented
I'll move this out of the beta milestone, thanks guys.

2024-07-20 01:50 UTC, notmandatory commented
This shouldn't break the `bdk_wallet` API but will require a sqlite schema migration. It's a good opportunity to demonstrate how to gracefully evolve the wallet `ChangeSet`.

2026-03-09 13:27 UTC, evanlinjin commented
This is unfortunately so outdated that it probably is better to start from scratch.

2026-03-09 13:27 UTC, closed without merging