Check recent blocks are not empty
bitcoindevkit/bdk pull request #1725
Opened 2024-11-16 20:02 UTC by rustaceanrob

Closes #1696 

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

2024-11-19 02:32 UTC, oleonardolima reviewed
It looks good, but it seems to partially address the problem.

I'm trying to wrap my mind on the behavior when the `latest_blocks` is empty. I wonder if it shouldn't be handled on the upstream fns too?

Otherwise, the same rogue Esplora server would still be able to crash the application as we expect to have a valid point of agreement here:
https://github.com/bitcoindevkit/bdk/blob/3bc45b5431014af3a8255a201e49227584e953b5/crates/esplora/src/blocking_ext.rs#L225

2024-11-19 02:40 UTC, rustaceanrob commented
That's a good point. I think these `is_empty` checks should simply be done in the first line of `chain_update` and this would be sufficient.

2024-11-19 16:53 UTC, oleonardolima reviewed
Concept ACK f3efbdaea95ceee762c31219f14a4181bcd92eeb

2024-11-21 03:22 UTC, notmandatory approved these changes
utACK f3efbdaea95ceee762c31219f14a4181bcd92eeb

2024-11-21 23:23 UTC, notmandatory commented
Can you add a simple test to exercise this condition in case we change the fix implementation later we make sure this remains fixed.

I also had some discussion with @oleonardolima and @ValuedMammal and it would be good to have the test first and make sure without any changes this does in fact gets to and fails an at expect.

2024-11-22 00:02 UTC, rustaceanrob commented
I can try to work on that tomorrow. Heads up I will not be able to work on much next week

2024-11-23 15:31 UTC, ValuedMammal commented
Since the checkpoint is an optional field of the sync/scan response it may also make sense to have `chain_update` return a `Result<Option<CheckPoint>, Error>`.

2024-11-23 17:46 UTC, rustaceanrob commented
I was thinking that this should be an error variant in the Esplora client, as it should not ever respond with empty blocks when requested. I am unable to do much this week but I can review any new PRs that replace this one

2024-12-03 12:18 UTC, evanlinjin requested changes

2024-12-03 12:18 UTC, evanlinjin commented on crates/esplora/src/async_ext.rs
> +    }
Please include docs explaining why we are doing this.

2024-12-03 12:22 UTC, evanlinjin commented
I'm thinking, if the server does something unexpected, maybe it is best to error out? Otherwise there is no way the caller will figure it out.

2024-12-03 17:00 UTC, rustaceanrob commented
> I'm thinking, if the server does something unexpected, maybe it is best to error out? Otherwise there is no way the caller will figure it out.

Right, I agree, but that would push the error variant into `rust_esplora_client` and would no longer be a `bdk_esplora` patch correct?

2024-12-04 01:59 UTC, rustaceanrob commented
Would be resolved by bitcoindevkit/rust-esplora-client#113

2024-12-04 23:05 UTC, rustaceanrob commented
Closed by bitcoindevkit/rust-esplora-client#113

2024-12-04 23:05 UTC, closed without merging