test(chain): add several basic scenarios to test transaction conflicts
bitcoindevkit/bdk pull request #1739
Opened 2024-11-21 12:46 UTC by pluveto

### Description

This update introduces several test cases to validate the transaction conflict handling logic within the `TxGraph`. The tests encompass a range of scenarios including:

1. Simple cases with isolated transactions (`only A exists`).
2. Scenarios with conflicting transactions (`B` and `B'` spending `A`) under two basic conditions:
   - One of the conflicting transactions is confirmed.
   - Conflicts are resolved based on the `last_seen` timestamp.

### Changelog Notice

- Added unit tests for transaction conflict resolution in `TxGraph`.

### Checklists

#### All Submissions:

* [x] I've signed all my commits.
* [x] I followed the [[contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md).
* [x] I ran `cargo fmt` and `cargo clippy` before committing.

2024-11-23 17:15 UTC, LagginTimes commented
Thank you for your contribution! The test case involving two conflicting transactions with different `last_seen` values is already addressed by the existing test scenario: "2 unconfirmed txs with same last_seens conflict." Other than that, the rest of the tests look good to me.

2024-11-24 03:22 UTC, pluveto commented
OK. I've removed this redundant case.

2024-11-24 08:57 UTC, LagginTimes commented
Could you please squash the second commit into the first one to keep the commit history clean? Everything will look good to me once that's done. Thanks!

2024-11-25 03:45 UTC, pluveto commented
Squash done.

2024-11-25 05:18 UTC, evanlinjin commented
@pluveto could you please rebase on master to fix CI? We just merged the fix for CI.

2024-11-25 06:57 UTC, pluveto commented
Now it's rebased.

2024-11-25 08:46 UTC, LagginTimes commented
ACK 8374f70b3428870a0ef5f77278329897464fee88

2024-11-25 23:54 UTC, evanlinjin approved these changes
ACK 8374f70b3428870a0ef5f77278329897464fee88

2024-11-25 23:54 UTC, evanlinjin commented on crates/chain/tests/test_tx_graph_conflicts.rs
> +            name: "B and B' spend A, B' is confirmed",
Nit: 
```suggestion
            name: "confirmed tx conflits with unconfirmed",
```

2024-11-26 13:08 UTC, LagginTimes commented on crates/chain/tests/test_tx_graph_conflicts.rs
> +            name: "confirmed tx conflits with unconfirmed",
There's a little documentation typo:

```suggestion
            name: "confirmed tx conflicts with unconfirmed",
```

2024-11-26 14:01 UTC, pluveto commented on crates/chain/tests/test_tx_graph_conflicts.rs
> +            name: "confirmed tx conflits with unconfirmed",
Fixed.

2024-11-27 14:37 UTC, LagginTimes commented
ACK 7c3f915886881c7d50e7f02eaef2774e63d1a3dc

2024-11-30 23:05 UTC, evanlinjin approved these changes
ACK 7c3f915886881c7d50e7f02eaef2774e63d1a3dc

2024-12-03 11:31 UTC, evanlinjin requested changes
In reality, this should really fail. A transaction that doesn't have a last-seen nor anchor should not be part of the best chain.

The culprit is the `TxTemplate` code (`crates/chain/tests/common/tx_template.rs`) which is wrong. I've fixed it in #1670.

Would you be able to rebase this on #1670?

2024-12-03 13:32 UTC, pluveto commented
Rebased

2024-12-12 16:27 UTC, oleonardolima reviewed
tACK 1cd0b4f91224727c6ead42c746642f1a300c6967

2026-06-15 21:08 UTC, evanlinjin commented
Stale

2026-06-15 21:08 UTC, closed without merging