Add testing on Compact Block filters in CI
bitcoindevkit/bdk pull request #668
Opened 2022-07-13 19:39 UTC by vladimirfomene

Setup testing on Compact block filters blockchain
backend.

### Description

While working on #634, I realized we don't have a setup for carrying out test on Compact Block Filters blockchain in CI. This PR is a work in progress solution to get that setup. 

### Notes to the reviewers
For some reason the tests are taking too long to run. 

![compact-block-filter-ci](https://user-images.githubusercontent.com/11140070/178816960-ffa6f85a-8677-417f-b4c2-e9540de13738.png)

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature
* [ ] I've updated `CHANGELOG.md`

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

2022-08-21 14:26 UTC, rajarshimaitra requested changes
Overall concept ACK on the idea of testing compact filter syncing in regtest.. Thanks for opening this up..  We might need this after integrating nakamoto too.. See here https://github.com/bitcoindevkit/bdk/issues/680#issuecomment-1221540035

But it needs the following additions to work properly..

2022-08-21 14:26 UTC, rajarshimaitra commented on src/blockchain/compact_filters/mod.rs
> +            CompactFiltersBlockchain::new(peers, "./wallet-filters", Some(0)).unwrap()
I haven't tested yet, but I don't think this logic will work.. 

 - You can't get compact filters from rpc port. You have to connect to the p2p port.
 - The test client doesn't serve compact filters by default. You need to set a extra bitcoind args parameter accordingly to turn that on the test client.. Which can be done under a feature gate..

2022-08-25 12:49 UTC, vladimirfomene commented
@rajarshimaitra , I will definitely get back to this once we integrate with Nakamoto.

2022-08-25 15:24 UTC, rajarshimaitra commented
Upon further thinking.. I think this can go into bdk even without nakamoto.. From the PoV of a testing framework we will always have only one single backend.. And CBF operation with single peer will be same between current bdk's cbf module and nakamoto.. 

So it might make sense to get this done even before we get nakamoto and bring the bdk's cbf impl into testing.. In that was when we shift to nakamoto we will already have a something to test it against in at least single peer scenario,.. 

So on high level what needs to be done to get compact_filters to testing is
 - Configure `bitcoind` in `TestClient` as compact blockfilter serving.. This should happen under a feature flag..
 - Get the p2p port of the bitcoind as pass that into compact filter blockchain.. 
  
@vladimirfomene if you are open to work on this I would suggest to carry on, as you are already quite close to the final thing..

2023-03-16 17:11 UTC, danielabrozzoni commented
Hey, we are in the process of releasing BDK 1.0, which will under the hood work quite differently from the current BDK. For this reason, I'm closing all the PRs that don't really apply anymore. If you think this is a mistake, feel free to rebase on master and re-open!

2023-03-16 17:11 UTC, closed without merging