Add `thiserror` for better display error formatting
bitcoindevkit/bdk pull request #813
Opened 2022-12-07 14:06 UTC by yukibtc

### Description

Resolve #555 

### Checklists

#### All Submissions:

* [X] I've signed all my commits
* [X] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [X] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [X] I'm linking the issue being fixed by this PR

2022-12-21 13:35 UTC, rajarshimaitra requested changes
Concept ACK..

One extra change for from impls as we are using `thiserror` so lets use its full power..

2022-12-21 13:35 UTC, rajarshimaitra commented on src/blockchain/compact_filters/mod.rs
>      Db(rocksdb::Error),
As we are using `thiserror` the from impls can also be automated using `Variant(#[from] Error_type)` syntax.. 

Same fro other conversions..

2022-12-23 10:12 UTC, rajarshimaitra reviewed
Review ACK.. Changes looks good to me.. Would let others comment with their take on using `thiserror` as a dep..

2022-12-31 20:06 UTC, notmandatory commented
I'm in favor of this approach, but since it's adding a new dependency I think we should discuss also at our next bdk dev call, I've added it to the agenda.

2023-01-03 18:30 UTC, notmandatory commented
@afilini in our call today we discussed making `thiserror` an optional dependency, but on second thought I don't think there's a reason make it optional since it [only adds macros](https://docs.rs/thiserror/latest/thiserror/#details) to generate nice looking `std::error::Error` implementations, so doesn't change the bdk lib API and has no requirement to also use `anyhow`.

2023-01-04 12:08 UTC, danielabrozzoni commented
> I don't think there's a reason to make it optional since it [only adds macros](https://docs.rs/thiserror/latest/thiserror/#details) to generate nice looking std::error::Error implementations

The reason for making it optional is that some projects want to cut dependencies to a minimum, and wouldn't use bdk if we include too many.

I agree with @afilini that it would be nice to have `thiserror` but behind a feature enabled by default

2023-01-04 13:10 UTC, yukibtc commented
Add `thiserror` as optional dependency, in my opinion, make the code more messed up, less maintainable.
If you prefer to have fewer dependencies, it's better to avoid to add `thiserror` also as optional dependency and continue in the way of PR #814.
The result of PR #813 and #814 for the dev that use BDK library is the same, but for you the work it's doubled when you need to make some changes to error enums (using the approach of `thiserror` as optional feature).
Keep both approach it's a bad idea, in my opinion.

2023-01-06 20:29 UTC, notmandatory commented
> Add `thiserror` as optional dependency, in my opinion, make the code more messed up, less maintainable. If you prefer to have fewer dependencies, it's better to avoid to add `thiserror` also as optional dependency and continue in the way of PR #814. The result of PR #813 and #814 for the dev that use BDK library is the same, but for you the work it's doubled when you need to make some changes to error enums (using the approach of `thiserror` as optional feature). Keep both approach it's a bad idea, in my opinion.

I agree if we want to avoid making `thiserror` a required dependency it's better to just go with your approach in #814. 

Reviewers, please check out #814, I've targeted it for the 0.27 release.

2023-02-01 09:57 UTC, closed without merging